apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liblaravel.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "liblaravel.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liblaravel.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'my-role'
        vault.hashicorp.com/agent-inject-secret-db-creds: 'database/creds/my-role'
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/creds/my-role" -}}
            export DB_USERNAME="{{ .Data.username }}"
            export DB_PASSWORD="{{ .Data.password }}"
          {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.image.port }}
          serviceAccountName: {{ include "liblaravel.fullname" . }}
          envFrom:
            - configMapRef:
                name: "{{ include "liblaravel.fullname" . }}-env"
      imagePullSecrets:
        - name: regcred