apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liblaravel.fullname" . }}-env
data:
  APP_DEBUG: "true"
  APP_ENV: "local"
  MIX_APP_ENV: "local"
  APP_NAME: "App"
  APP_LABEL: {{ quote .Values.ingress.host }}
  APP_DOMAIN: {{ quote .Values.ingress.host }}
  APP_URL: "http://{{ .Values.ingress.host }}"
  APP_KEY: "base64:fJZN6TrXzqgb6ppUrpV27n49wb3S+o3Q4Odm5zZWosY="
  DB_CONNECTION: "mysql"
  DB_HOST: {{ quote .Values.database.host }}
  DB_DATABASE: {{ quote .Values.database.name }}

