{{- define "liblaravel.ingress.tpl" -}}
{{- $fullName := include "liblaravel.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
            path: /
            pathType: Prefix
    {{- end }}
{{- end -}}
{{- define "liblaravel.ingress" -}}
{{- include "liblaravel.util.merge" (append . "liblaravel.ingress.tpl") -}}
{{- end -}}
