{{- define "liblaravel.secrets.tpl" -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "liblaravel.fullname" . }}-secrets
  namespace: default
  #annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
  #  sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    name: {{ include "liblaravel.fullname" . }}-secrets
    metadata:
        {{- include "liblaravel.selectorLabels" . | nindent 6 }}
    type: Opaque

  encryptedData:
    {{ if eq .Values.env "prod" }}
    foo1: "AgAkaTBYcESwogPi...",
    foo2: "AgAkaTBYcESwogPi...",
    {{ else if eq .Values.env "dev" }}
    foo: "AgAkaTBYcESwogPi..."
    {{ end }}
{{- end -}}
{{- define "liblaravel.secrets" -}}
{{- include "liblaravel.util.merge" (append . "liblaravel.secrets.tpl") -}}
{{- end -}}
