{{- include "liblaravel.secrets" (list . "bim-company.secrets") -}}
{{- define "bim-company.secrets" -}}
encryptedData:
  {{ if eq .Values.env "prod" }}
  foo1: "AgAkaTBYcESwogPi...",
  foo2: "AgAkaTBYcESwogPi...",
  {{ else if eq .Values.env "dev" }}
  foo: "AgAkaTBYcESwogPi..."
  {{ end }}

{{- end -}}